### ISSUE TITLE
Parser for teamspeak query port

### ISSUE THREAD

**Issue by qshane** [FCoQ/dobby#1]
Dobby needs a parser for the teamspeak query port protocol. It's plaintext, but it's a little messy. We can take inspiration from a PEG parser I wrote [here](https://github.com/qshane/old-dobby/blob/master/src/command.rs). Javascript has peg.js, so we can use that.

**Comment by quibsorg** [comment]
https://www.npmjs.com/package/node-teamspeak

Check this out, we can definitely utilize this tool.

**Comment by qshane** [comment]
We're using a fork of node-teamspeak now: https://github.com/qshane/node-teamspeak
